---
- name: Install Java 8
  become: yes
  hosts: all
  tasks:
    - name: Update packages
      apt:
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Install openjdk 8 
      package:
        name: "{{ java_package }}"
        state: present