---
- name: Install dotnet 6 on ubuntu 20.04
  become: yes
  hosts: all
  tasks:

    - name: Download and save Microsoft packages for ubuntu
      ansible.builtin.get_url:
        url: "https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb"
        dest: "/tmp/packages-microsoft-prod.deb"

    - name: Install downloaded dpkg packages
      ansible.builtin.dpkg_selections:
        name: packages-microsoft-prod.deb
        selection: install
      notify: Update packages

    - name: Copy preferences file
      ansible.builtin.copy:
        src: 'preferences'
        dest: /etc/apt/preferences
        owner: root
        group: root
        mode: '0644'
      notify: Update packages

    - name: Install dotnet core sdk 6.0
      community.general.plugins.module_utils.cmd_runner:
        name: 'dotnet-sdk'
        channel: 6.0
        classic: yes
        state: present

  handlers:
    - name: Update packages
      apt:
        update_cache: yes
